config/routes.rb
DashCreator::Engine.routes.draw do
  root to: 'user#creator'

  get '/creator', to: 'user#creator', as: :creator
  get '/dashboard/:dashboard_id', to: 'user#dashboard', as: :dashboard

  post '/get_filter', to: 'filter#get_filter', as: :get_filter
  post '/save_filter', to: 'filter#save_filter', as: :save_filter
  post '/delete_filters', to: 'filter#delete_filters', as: :delete_filters

  post '/filtering_result', to: 'filter#filtering_result', as: :filtering_result
  get '/download_csv', to: 'filter#download_csv', as: :download_csv

  post '/create_stat', to: 'filter#create_stat', as: :create_stat

  post '/create_chart', to: 'chart#create_chart', as: :create_chart
  post '/save_chart', to: 'chart#save_chart', as: :save_chart
  post '/edit_chart', to: 'chart#edit_chart', as: :edit_chart
  post '/get_chart', to: 'chart#get_chart', as: :get_chart
  post '/delete_charts', to: 'chart#delete_charts', as: :delete_charts

  post '/pluck_labels', to: 'chart#pluck_labels', as: :pluck_labels

  post '/save_dashboard', to: 'dashboard#save_dashboard', as: :save_dashboard
  post '/edit_dashboard', to: 'dashboard#edit_dashboard', as: :edit_dashboard
  post '/get_dashboard', to: 'dashboard#get_dashboard', as: :get_dashboard
  post '/delete_dashboards', to: 'dashboard#delete_dashboards', as: :delete_dashboards

  post '/get_model_objects', to: 'dashboard_object#get_model_objects', as: :get_model_objects
end

app/models/dash_creator/application_record.rb
module DashCreator
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/dash_creator/dashboard_object.rb
module DashCreator
  class DashboardObject < ApplicationRecord
    validates_presence_of :code, unique: true

    # Acts as dashboard object for objects you want to display in your dashboard
  end
end

app/controllers/dash_creator/application_controller.rb
class DashCreator::ApplicationController < ::ApplicationController
  protect_from_forgery with: :exception
end

app/controllers/dash_creator/chart_controller.rb
require_dependency "dash_creator/application_controller"

module DashCreator
  class ChartController < ApplicationController
    skip_before_action :verify_authenticity_token
    
    def create_chart
      return render json: {models: nil} if params[:filters].nil?

      # Remove useless filters from data
      chart_data = params
      chart_data[:filters] = chart_data[:filters]
                                 .to_unsafe_h
                                 .select { |key, value| chart_data[:y_data].include?(key.to_s) || (key.to_s == chart_data[:x_data][:attribute].classify && chart_data[:x_data][:from_filter] == 'true' ) }

      render 'dash_creator/chart/create_chart', locals: {chart_data: chart_data, filters_data: nil, id: 0}
    end

    def save_chart
      return render json: {models: nil} if params[:filters].nil?

      # Remove useless filters from data
      chart_data = params
      chart_data[:filters] = chart_data[:filters]
                                 .to_unsafe_h
                                 .select { |key, value| chart_data[:y_data].include?(key.to_s) || (key.to_s == chart_data[:x_data][:attribute].classify && chart_data[:x_data][:from_filter] == 'true' ) }

      # Create chart from data
      user = user_for_dash_creator
      chart = DashCreator::Chart.all.where(user_id: user.id).create(name: params[:chart_name], data: chart_data)

      render json: {chart_id: chart.id}
    end

    def edit_chart
      return render json: {models: nil} if params[:filters].nil?

      # Remove useless filters from data
      chart_data = params
      chart_data[:filters] = chart_data[:filters]
                                 .to_unsafe_h
                                 .select { |key, value| chart_data[:y_data].include?(key.to_s) || (key.to_s == chart_data[:x_data][:attribute].classify && chart_data[:x_data][:from_filter] == 'true' ) }

      # Edit chart from data
      user = user_for_dash_creator
      chart = DashCreator::Chart.all.where(user_id: user.id).find(params[:chart_id])
      chart.update_attribute(:data, chart_data)

      render json: {chart_id: chart.id}
    end

    def get_chart
      user = user_for_dash_creator
      id = params[:chart_id]
      chart = DashCreator::Chart.all.where(user_id: user.id).find(id)
      refresh = params.key?('refresh') ? params['refresh'] : 'false'

      filters_data = chart.data['filters']

      chart_data = chart.data
      chart_data['refresh'] = refresh
      chart_data.delete('chart_id')
      chart_data.delete('chart_name')

      render 'dash_creator/chart/create_chart', locals: {chart_data: chart.data, filters_data: filters_data, id: id}
    end

    def delete_charts
      user = user_for_dash_creator
      DashCreator::Chart.all.where(user_id: user.id, id: params[:charts_ids]).destroy_all
    end

    def pluck_labels
      model = params[:model].safe_constantize
      attribute = params[:attribute]
      limit = params[:limit].empty? ? 30 : params[:limit].to_i

      render json: {labels: model.pluck(:"#{attribute}").uniq.take(limit)}
    end
  end
end

app/controllers/dash_creator/dashboard_controller.rb
require_dependency "dash_creator/application_controller"

module DashCreator
  class DashboardController < ApplicationController
    skip_before_action :verify_authenticity_token

    def get_dashboard
      # user = user_for_dash_creator
      # dashboard = DashCreator::Dashboard.all.where(user_id: user.id).find(params[:dashboard_id])
      dashboard = DashCreator::Dashboard.all.find(params[:dashboard_id])

      render json: dashboard.options
    end

    def save_dashboard
      user = user_for_dash_creator
      dashboard = DashCreator::Dashboard.all.where(user_id: user.id).create(name: params[:dashboard_name], options: params[:options])

      render json: {dashboard_id: dashboard.id}
    end

    def edit_dashboard
      # user = user_for_dash_creator
      # dashboard = DashCreator::Dashboard.all.where(user_id: user.id).find(params[:dashboard_id])
      dashboard = DashCreator::Dashboard.all.find(params[:dashboard_id])
      dashboard.update_attribute(:options, params[:options])

      render json: {dashboard_id: dashboard.id}
    end

    def delete_dashboards
      # user = user_for_dash_creator
      # DashCreator::Dashboard.all.where(user_id: user.id, id: params[:dashboards_ids]).destroy_all
      DashCreator::Dashboard.all.where(id: params[:dashboards_ids]).destroy_all
    end
  end
end

app/controllers/dash_creator/dashboard_object_controller.rb
require_dependency "dash_creator/application_controller"

module DashCreator
  class DashboardObjectController < ApplicationController
    skip_before_action :verify_authenticity_token

    def get_model_objects
      object = DashboardObject.find_by_code(params['object_code'])

      model_objects = object.related_model.classify.safe_constantize.all

      model_objects_json = model_objects.map{ |o| {id: o.id, name: o.name} }

      render json: {model_objects: model_objects_json}
    end

    def save_object
      object = DashboardObject.create(name: params[:name], options: params[:options])

      render json: {object_id: object.id}
    end

    def edit_object
      object = DashboardObject.find_by_code(params['object_code'])
      object.update_attribute(:options, params[:options])

      render json: {object_id: object.id}
    end

    def delete_object
      DashboardObject.find(params[:object_id]).destroy
    end
  end
end

app/helpers/dash_creator/application_helper.rb
module DashCreator
  module ApplicationHelper
  end
end

app/helpers/dash_creator/chart_helper.rb
module DashCreator
  module ChartHelper
    def plot_chart(id, type, plot_data, options = {})
      default_options = {
          tooltips: {
              mode: 'nearest',
              intersect: false
          },
          responsive: true
      }
      options = options.merge(default_options)
      render 'dash_creator/chart/plot_chart', {id: id, type: type, data: plot_data, options: options}
    end

    def create_update_button(id, type, text)
      button_tag text, id: "btn-#{type}-#{id}"
    end

    def update_chart_script(id, type, action_path, action_params = {})
      render 'dash_creator/chart/update_chart', {id: id, type: type, action_path: action_path, action_params: action_params}
    end

    # Data formatting (hash)
    # :labels is array of labels
    # :datasets_labels is array of datasets labels
    # :datasets is array of arrays containing the datasets data
    # for a mixed chart, :types is array of datasets types
    # :style contains chart styling
    def plot_type_1_chart(id, type, data, options = {})
      begin
        raise ArgumentError, 'datasets_key_missing' unless data.key?('datasets')
        raise ArgumentError, 'labels_key_missing' unless data.key?('labels')
        raise ArgumentError, 'types_key_missing' if (type == 'mixed' && !data.key?('types'))

        plot_data = type_1_data_to_plot(data)
      rescue Exception => e
        return render html: create_plot_error_message(id, type, e.message).to_s
      end
      plot_data_with_options = type_1_add_style(plot_data, data['style'])
      plot_data_with_options[:options] = plot_data_with_options[:options].merge(options)

      plot_chart(id, type, plot_data_with_options[:plot_data], plot_data_with_options[:options])
    end

    def type_1_data_to_plot(data)
      datasets = []
      0.upto(data['datasets'].length-1) do |i|
        set = {data: data['datasets'][i]}
        unless data['labels'][i].nil?
          set[:label] = data['datasets_labels'][i] unless data['datasets_labels'].nil?
        end
        set[:type] = data['types'][i]
        datasets.push(set)
      end

      {labels: data['labels'], datasets: datasets}
    end

    def type_1_add_style(plot_data, style_options)
      colors = style_options['colors'].nil? ? nil : set_transparency(style_options['colors'], style_options['transparencies'])

      0.upto(plot_data[:datasets].length-1) do |i|
        set = plot_data[:datasets][i]
        set[:backgroundColor] = colors[i] unless colors.nil? || colors[i].nil?
        set[:borderColor] = style_options['colors'][i] unless style_options['colors'].nil? || style_options['colors'][i].nil?
      end

      # Initialize options
      options = {}
      scales = options['scales'] = {}
      scales['xAxes'] = [{}]
      scales['yAxes'] = [{}]
      scales['xAxes'][0]['gridLines'] = {}
      scales['xAxes'][0]['ticks'] = {}
      scales['yAxes'][0]['gridLines'] = {}
      scales['yAxes'][0]['ticks'] = {}

      # Grid options
      grid_options = style_options['grid']
      scales['xAxes'][0]['gridLines']['display'] = false if grid_options['x'] == 'false'
      scales['yAxes'][0]['gridLines']['display'] = false if grid_options['y'] == 'false'

      # Y Axis options
      y_axis_options = style_options['y-axis']
      scales['yAxes'][0]['ticks']['min'] = y_axis_options['min'].to_i if y_axis_options['min'] != ''
      scales['yAxes'][0]['ticks']['max'] = y_axis_options['max'].to_i if y_axis_options['max'] != ''
      scales['yAxes'][0]['ticks']['stepSize'] = y_axis_options['step'].to_i if y_axis_options['step'] != ''

      # Stacked
      if style_options['stacked'] == 'true'
        scales['xAxes'][0]['stacked'] = true
        scales['yAxes'][0]['stacked'] = true
      end

      # Labeling step
      scales['xAxes'][0]['ticks']['callback'] = style_options['labeling-step'] if style_options['labeling-step'] != ''

      # Legend
      legend_options = style_options['legend']
      legend = options['legend'] = {}
      legend['display'] = false if legend_options['display'] == 'false'
      legend['position'] = legend_options['position']

      # Title
      options['title'] = {display: true, text: style_options['title']} if style_options['title'] != ''

      {plot_data: plot_data, options: options}
    end



    # Data formatting (hash)
    # :labels is array of labels
    # :datasets is array of arrays containing the datasets data
    # :style contains chart styling
    def plot_type_2_chart(id, type, data, options = {})
      begin
        raise ArgumentError, 'datasets_key_missing' unless data.key?('datasets')
        raise ArgumentError, 'labels_key_missing' unless data.key?('labels')

        plot_data = type_2_data_to_plot(data)
      rescue Exception => e
        return render html: create_plot_error_message(id, type, e.message).to_s
      end
      plot_data_with_options = type_2_add_style(plot_data, data['style'])
      plot_data_with_options = plot_data_with_options.merge(options)

      plot_chart(id, type, plot_data_with_options[:plot_data], plot_data_with_options[:options])
    end

    def type_2_data_to_plot(data)
      datasets = []
      0.upto(data['datasets'].length-1) do |i|
        set = {
            data: data['datasets'][i]
        }
        datasets.push(set)
      end

      {labels: data['labels'], datasets: datasets}
    end

    def type_2_add_style(plot_data, style_options)
      0.upto(plot_data[:datasets].length-1) do |i|
        set = plot_data[:datasets][i]
        set[:backgroundColor] = set_transparency(style_options['colors'], style_options['transparencies']) unless style_options['colors'].nil?
      end

      options = {}

      legend_options = style_options['legend']
      legend = options['legend'] = {}
      legend['display'] = false if legend_options['display'] == 'false'
      legend['position'] = legend_options['position']

      options['title'] = {display: true, text: style_options['title']} if style_options['title'] != ''

      {plot_data: plot_data, options: options}
    end


    # Type 1 charts & mixed bar/line
    def plot_line_chart(id, data, options = {})
      plot_type_1_chart(id, 'line', data, options)
    end

    def plot_bar_chart(id, data, options = {})
      plot_type_1_chart(id, 'bar', data, options)
    end

    def plot_mixed_chart(id, data, options = {})
      plot_type_1_chart(id, 'mixed', data, options)
    end


    # Type 2 charts
    def plot_pie_chart(id, data, options = {})
      plot_type_2_chart(id, 'pie', data, options)
    end

    def plot_doughnut_chart(id, data, options = {})
      plot_type_2_chart(id, 'doughnut', data, options)
    end

    def plot_polar_chart(id, data, options = {})
      plot_type_2_chart(id, 'polarArea', data, options)
    end

    def plot_radar_chart(id, data, options = {})
      plot_type_2_chart(id, 'radar', data, options)
    end


    # From rgb to rgba with given colors and transparencies
    def set_transparency(colors, transparencies)
      colors_with_transparency = []
      0.upto(colors.length - 1).each { |i| colors_with_transparency.push('rgba' + colors[i][3..-2] + ', ' + (1-(transparencies[i].to_f/100)).to_s + ')') }
      colors_with_transparency
    end

    # Returns plot failing error message
    def create_plot_error_message(id, type, error_key)
      str = error_key + " for chart-#{type}-#{id}"
      str
    end


    # Data processing for charts
    # Handle differently regarding x_data type
    def chart_processing(data)
      ActiveRecord::Base.connection.execute("SET temp_buffers = '4GB';")
      case data['x_data']['type']
        when 'datetime'
          hash = date_chart_processing(data)

        when 'numeric'
          hash = numeric_chart_processing(data)

        when 'boolean'
          hash = boolean_chart_processing(data)

        when 'text'
          hash = text_chart_processing(data)

        when 'has'
          hash = has_model_chart_processing(data)

        when 'ref'
          hash = ref_model_chart_processing(data)

        else
          hash = {}
      end
      ActiveRecord::Base.connection.execute("SET temp_buffers = '8MB';")
      hash = hash.merge({
                            datasets_labels: data['datasets_labels'],
                            types: data['types']
                        })
      hash
    end

    def get_start_and_end_dates(date_info)
      date_range_type = date_info['date_range_type']

      case date_range_type
        when 'Today'
          start_date = DateTime.now.beginning_of_day
          end_date = DateTime.now.beginning_of_day + 1.days

        when 'Yesterday'
          start_date = DateTime.now.beginning_of_day - 1.days
          end_date = DateTime.now.beginning_of_day

        when 'Last 7 Days'
          start_date = DateTime.now.beginning_of_day - 6.days
          end_date = DateTime.now.beginning_of_day + 1.days

        when 'This Week'
          start_date = DateTime.now.beginning_of_week
          end_date = DateTime.now.beginning_of_week + 7.days

        when 'Last Week'
          start_date = DateTime.now.beginning_of_week - 7.days
          end_date = DateTime.now.beginning_of_week

        when 'Last 30 Days'
          start_date = DateTime.now.beginning_of_day - 29.days
          end_date = DateTime.now.beginning_of_day + 1.days

        when 'This Month'
          start_date = DateTime.now.beginning_of_month
          end_date = DateTime.now.beginning_of_month + 30.days

        when 'Last Month'
          start_date = DateTime.now.beginning_of_month - 30.days
          end_date = DateTime.now.beginning_of_month

        when 'Last 365 Days'
          start_date = DateTime.now.beginning_of_day - 364.days
          end_date = DateTime.now.beginning_of_day + 1.days

        when 'This Year'
          start_date = DateTime.now.beginning_of_year
          end_date = DateTime.now.beginning_of_year + 365.days

        when 'Last Year'
          start_date = DateTime.now.beginning_of_year - 365.days

app/helpers/dash_creator/dashboard_helper.rb
module DashCreator
  module DashboardHelper
  end
end

app/helpers/dash_creator/dashboard_object_helper.rb
module DashCreator
  module DashboardObjectHelper
  end
end

app/helpers/dash_creator/user_helper.rb
module DashCreator
  module UserHelper
  end
end

app/views/dash_creator/filter/_filtering_card.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        Filters
      </div>
      <div class="card-block" id="filter-creator">
      </div>
      <div class="card-footer">
        <button type="submit" class="pull-left btn btn-success" id="apply-btn">Apply filtering</button>
        <a href="#" data-toggle="modal" data-target="#delete_filters_modal" class="pull-right btn btn-sm btn-danger" id="unsave-btn"><%=t :delete_filters%></a>
        <a href="#" data-toggle="modal" data-target="#save_filter_modal" class="pull-right btn btn-sm btn-success"><%=t :save_filter%></a>
        <select name="filter-select" class="form-control pull-right" style="width: 20%; margin-right: 10%;">
          <option value="">Choose a filter</option>
        </select>
      </div>
    </div>
    <!--/.card-->
  </div>
</div>

<div class="container" id="result-container">
</div>

<script>
    var filters = <%= raw @filters %>;

    var models_data = <%= raw @models_data.to_json %>;

    $('#filter-creator').filterCreator({
        models_data: models_data,
        attributes_aliases: <%= raw DashCreator.attributes_aliases.to_json %>,
        displayed_model_names: <%= raw DashCreator.displayed_model_names.to_json %>,
        displayed_attribute_names: <%= raw DashCreator.displayed_attribute_names.to_json %>
    });
    var filter_creator = $('#filter-creator').data('filterCreator');


    // --------------- Send data ---------------
    $('#apply-btn').click(sendFilterData);
    function sendFilterData() {
        var params = {
            filters: filter_creator.getFiltersData(),
            id: 0
        };

        // Post filters
        $.post("<%= filtering_result_path %>", params);
    }


    // --------------- Save & delete saved filters ---------------
    // Save a filter config
    $(document).on('click', '#save-filter-btn', function() {
        var params = {filters: filter_creator.getFiltersData()};

        // Get the filter name
        params['filter_name'] = $('.modal').find('[name="filter-name"]').val();

        $.post("<%= save_filter_path %>", params, function(data) {
            // Add to filters list
            filters.push([params['filter_name'], data['filter_id']]);
        });
    });

    // Prepare list of filters for delete filters modal
    $('#unsave-btn').click(function() {
        var filters_checkbox_list = $('#filters-checkbox-list');
        // First empty the checkbox list
        filters_checkbox_list.children().remove();

        // Append filters list to div in modal
        var checkbox_string_start = '<div class="col-sm-12"><div class="form-group">'
            + '<input type="checkbox" class="form-control" name="filter" value="';
        for (var i = 0; i < filters.length; i++) {
            var filter_name = filters[i][0], filter_id = filters[i][1];
            var filter_string = checkbox_string_start + filter_id + '"><label>' + filter_name + '</label><br>';
            $(filter_string).appendTo(filters_checkbox_list);
        }
        $('</div></div>').appendTo(filters_checkbox_list);
    });

    // Delete filters configs
    $(document).on('click', '#delete-filters-btn', function() {
        // Get the filters ids
        var filters_ids = [];
        $(this).closest('.modal').find('[type="checkbox"]:checked').each(function() {
            filters_ids.push($(this).attr("value"));
        });

        var params = {filters_ids: filters_ids};

        $.post("<%= delete_filters_path %>", params, function() {
            // Remove from filters list
            for (var i = 0; i < filters.length; i++) {
                var filter_id = filters[i][1];
                if ($.inArray(filter_id, filters_ids) !== -1) {
                    filters.splice(i, 1);
                    i--;
                }
            }
        });
    });


    // --------------- Display save filter ---------------
    $('[name="filter-select"]')
        .focusin(displaySavedFilters)
        .change(displayFilter);

    // Display saved configs
    function displaySavedFilters() {
        $(this).children().not('[value=""]').remove();
        for (var i = 0; i < filters.length; i++) {
            var filter_name = filters[i][0], filter_id = filters[i][1];
            $('<option value="' + filter_id + '">' + filter_name + '</option>').appendTo($('[name="filter-select"]'));
        }
    }

    // Display chosen config (rebuild)
    function displayFilter() {
        var filter_id = $(this).val();
        if (filter_id === '')
            return false;

        var params = {filter_id: filter_id};

        $.post("<%= get_filter_path %>", params, function(data) {
            filter_creator.buildFilters(data);
        });
    }
</script>

app/views/dash_creator/filter/_modals.html.erb
<div class="modal fade" id="save_filter_modal" tabindex="-1" role="dialog" aria-labelledby="Save Filter Modal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><%=t :save_filter%></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <label><%=t :name%></label>
              <input type="text" name="filter-name" class="form-control">
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="pull-right btn btn-success" id="save-filter-btn" data-dismiss="modal">Submit</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="modal fade" id="delete_filters_modal" tabindex="-1" role="dialog" aria-labelledby="Delete Filters Modal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><%=t :delete_filters%></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row" id="filters-checkbox-list">
        </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="pull-right btn btn-success" id="delete-filters-btn" data-dismiss="modal">Submit</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

app/views/dash_creator/filter/_result_tables.html.erb
<% unless mods.nil? %>
  <% mods.each do |model, objects| %>
    <% next if objects.nil? || objects.empty? %>

    <% model_attributes = objects.first.class.columns_hash %>

    <div class="row">
      <div class="col-md-12">
        <h3 class="text-center"><%= model %></h3><br>

        <div>
          <a href="" target="_blank" class="btn btn-primary csv-download" data-model="<%= model %>" data-turbolinks="false">Download CSV</a>
        </div>

      </div>
      <div class="col-md-2">
        <% model_attributes.each do |attribute, value| %>
            <% if @starting_types.include?(value.type.to_s) %>
                <input type="checkbox" name="<%= model %>" value="<%= attribute %>" checked="checked">

            <% else %>
                <input type="checkbox" name="<%= model %>" value="<%= attribute %>">

            <% end %>

            <label><%= attribute.humanize %></label><br>
        <% end %>
      </div>
      <div class="offset-md-2 col-md-8">
        <table class="table table-hover table-outline mb-0 hidden-sm-down" name="<%= model %>">
          <thead class="thead-default">
          <tr>
            <% model_attributes.each do |attribute, value| %>
                <th class="text-center" value="<%= attribute %>"><%= attribute.humanize %></th>
            <% end %>
          </tr>
          </thead>

          <tbody>
          <% objects.each do |object| %>
              <tr>
                <% object.attributes.each do |key, value| %>
                    <td value="<%= key %>"><%= value %></td>
                <% end %>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <% if mods.length > 1 %>
        <hr><br>
    <% end %>
  <% end %>
<% end %>

app/views/dash_creator/filter/apply_filtering.js.erb
var in_creator = <%= id == 0 %>;

<% mods = filter_data(data) %>

var result_container = in_creator ? $('#result-container') : $('.table-wrapper[data-id="<%= id %>"]');

var results_string = '<%= raw "#{render 'result_tables', {mods: mods}}".gsub("\n", '') %>';
result_container.children().remove();
$(results_string).appendTo(result_container);

result_container.find('[type="checkbox"]').each(updateTableColumns);

function updateTableColumns() {
    var name = $(this).attr("name"), value = $(this).attr("value");
    var change_column = result_container.find('table[name="' + name + '"]').find('[value="' + value + '"]');
    this.checked ? change_column.show() : change_column.hide();
}

function downloadCSV() {
    <% mods.each do |model, objects| %>

    var columns = [];
    result_container.find('[name="<%= model %>"]:checked').each(function() {
        columns.push($(this).val());
    });

    var ids = <%= raw objects.map{ |o| o.id } %>;

    var params = {
        model: "<%= model %>",
        columns: columns,
        ids: ids
    };
    var url_params = $.param(params);

    var link = '<%= download_csv_path %>?' + url_params;
    var download_csv_link = result_container.find('[data-model="<%= model %>"]');
    download_csv_link.attr("href", link);

    <% end %>
}

result_container
    .off("click")
    .on("click", '[type="checkbox"]', updateTableColumns)
    .on("click", '.csv-download', downloadCSV);

app/views/dash_creator/filter/create_stat.js.erb
var stat_wrapper = $('.stat-wrapper[data-id="<%= id %>"]');

<% data = filter_data_count_from_redis(filters_data.deep_stringify_keys) %>
<% last_updated = data.delete('last_updated') %>

stat_wrapper.find('#last-updated').text('<%= last_updated %>');

<% data.keys.each do |k| %>
  stat_wrapper.find('.filter-count[data-key="<%= k %>"]').text('<%= data[k] %>');
<% end %>

stat_wrapper.off("click").on("click", "#stat-refresh-btn", function() {
    var params = {
        filter_id: '<%= id %>',
        refresh: true
    };
    $.post("<%= create_stat_path %>", params);
});

<% # DashCreator.redis_store_variable.keys.each {|k| $redis.del(k)}   # To delete what is stored in redis %>