config/routes.rb
DashCreator::Engine.routes.draw do
  root to: 'user#creator'

  get '/creator', to: 'user#creator', as: :creator
  get '/dashboard/:dashboard_id', to: 'user#dashboard', as: :dashboard

  post '/get_filter', to: 'filter#get_filter', as: :get_filter
  post '/save_filter', to: 'filter#save_filter', as: :save_filter
  post '/delete_filters', to: 'filter#delete_filters', as: :delete_filters

  post '/filtering_result', to: 'filter#filtering_result', as: :filtering_result
  get '/download_csv', to: 'filter#download_csv', as: :download_csv

  post '/create_stat', to: 'filter#create_stat', as: :create_stat

  post '/create_chart', to: 'chart#create_chart', as: :create_chart
  post '/save_chart', to: 'chart#save_chart', as: :save_chart
  post '/edit_chart', to: 'chart#edit_chart', as: :edit_chart
  post '/get_chart', to: 'chart#get_chart', as: :get_chart
  post '/delete_charts', to: 'chart#delete_charts', as: :delete_charts

  post '/pluck_labels', to: 'chart#pluck_labels', as: :pluck_labels

  post '/save_dashboard', to: 'dashboard#save_dashboard', as: :save_dashboard
  post '/edit_dashboard', to: 'dashboard#edit_dashboard', as: :edit_dashboard
  post '/get_dashboard', to: 'dashboard#get_dashboard', as: :get_dashboard
  post '/delete_dashboards', to: 'dashboard#delete_dashboards', as: :delete_dashboards

  post '/get_model_objects', to: 'dashboard_object#get_model_objects', as: :get_model_objects
end

app/models/dash_creator/application_record.rb
module DashCreator
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/dash_creator/dashboard_object.rb
module DashCreator
  class DashboardObject < ApplicationRecord
    validates_presence_of :code, unique: true

    # Acts as dashboard object for objects you want to display in your dashboard
  end
end

app/controllers/dash_creator/application_controller.rb
class DashCreator::ApplicationController < ::ApplicationController
  protect_from_forgery with: :exception
end

app/controllers/dash_creator/chart_controller.rb
require_dependency "dash_creator/application_controller"

module DashCreator
  class ChartController < ApplicationController
    skip_before_action :verify_authenticity_token
    
    def create_chart
      return render json: {models: nil} if params[:filters].nil?

      # Remove useless filters from data
      chart_data = params
      chart_data[:filters] = chart_data[:filters]
                                 .to_unsafe_h
                                 .select { |key, value| chart_data[:y_data].include?(key.to_s) || (key.to_s == chart_data[:x_data][:attribute].classify && chart_data[:x_data][:from_filter] == 'true' ) }

      render 'dash_creator/chart/create_chart', locals: {chart_data: chart_data, filters_data: nil, id: 0}
    end

    def save_chart
      return render json: {models: nil} if params[:filters].nil?

      # Remove useless filters from data
      chart_data = params
      chart_data[:filters] = chart_data[:filters]
                                 .to_unsafe_h
                                 .select { |key, value| chart_data[:y_data].include?(key.to_s) || (key.to_s == chart_data[:x_data][:attribute].classify && chart_data[:x_data][:from_filter] == 'true' ) }

      # Create chart from data
      user = user_for_dash_creator
      chart = DashCreator::Chart.all.where(user_id: user.id).create(name: params[:chart_name], data: chart_data)

      render json: {chart_id: chart.id}
    end

    def edit_chart
      return render json: {models: nil} if params[:filters].nil?

      # Remove useless filters from data
      chart_data = params
      chart_data[:filters] = chart_data[:filters]
                                 .to_unsafe_h
                                 .select { |key, value| chart_data[:y_data].include?(key.to_s) || (key.to_s == chart_data[:x_data][:attribute].classify && chart_data[:x_data][:from_filter] == 'true' ) }

      # Edit chart from data
      user = user_for_dash_creator
      chart = DashCreator::Chart.all.where(user_id: user.id).find(params[:chart_id])
      chart.update_attribute(:data, chart_data)

      render json: {chart_id: chart.id}
    end

    def get_chart
      user = user_for_dash_creator
      id = params[:chart_id]
      chart = DashCreator::Chart.all.where(user_id: user.id).find(id)
      refresh = params.key?('refresh') ? params['refresh'] : 'false'

      filters_data = chart.data['filters']

      chart_data = chart.data
      chart_data['refresh'] = refresh
      chart_data.delete('chart_id')
      chart_data.delete('chart_name')

      render 'dash_creator/chart/create_chart', locals: {chart_data: chart.data, filters_data: filters_data, id: id}
    end

    def delete_charts
      user = user_for_dash_creator
      DashCreator::Chart.all.where(user_id: user.id, id: params[:charts_ids]).destroy_all
    end

    def pluck_labels
      model = params[:model].safe_constantize
      attribute = params[:attribute]
      limit = params[:limit].empty? ? 30 : params[:limit].to_i

      render json: {labels: model.pluck(:"#{attribute}").uniq.take(limit)}
    end
  end
end

app/controllers/dash_creator/dashboard_controller.rb
require_dependency "dash_creator/application_controller"

module DashCreator
  class DashboardController < ApplicationController
    skip_before_action :verify_authenticity_token

    def get_dashboard
      # user = user_for_dash_creator
      # dashboard = DashCreator::Dashboard.all.where(user_id: user.id).find(params[:dashboard_id])
      dashboard = DashCreator::Dashboard.all.find(params[:dashboard_id])

      render json: dashboard.options
    end

    def save_dashboard
      user = user_for_dash_creator
      dashboard = DashCreator::Dashboard.all.where(user_id: user.id).create(name: params[:dashboard_name], options: params[:options])

      render json: {dashboard_id: dashboard.id}
    end

    def edit_dashboard
      # user = user_for_dash_creator
      # dashboard = DashCreator::Dashboard.all.where(user_id: user.id).find(params[:dashboard_id])
      dashboard = DashCreator::Dashboard.all.find(params[:dashboard_id])
      dashboard.update_attribute(:options, params[:options])

      render json: {dashboard_id: dashboard.id}
    end

    def delete_dashboards
      # user = user_for_dash_creator
      # DashCreator::Dashboard.all.where(user_id: user.id, id: params[:dashboards_ids]).destroy_all
      DashCreator::Dashboard.all.where(id: params[:dashboards_ids]).destroy_all
    end
  end
end

app/controllers/dash_creator/dashboard_object_controller.rb
require_dependency "dash_creator/application_controller"

module DashCreator
  class DashboardObjectController < ApplicationController
    skip_before_action :verify_authenticity_token

    def get_model_objects
      object = DashboardObject.find_by_code(params['object_code'])

      model_objects = object.related_model.classify.safe_constantize.all

      model_objects_json = model_objects.map{ |o| {id: o.id, name: o.name} }

      render json: {model_objects: model_objects_json}
    end

    def save_object
      object = DashboardObject.create(name: params[:name], options: params[:options])

      render json: {object_id: object.id}
    end

    def edit_object
      object = DashboardObject.find_by_code(params['object_code'])
      object.update_attribute(:options, params[:options])

      render json: {object_id: object.id}
    end

    def delete_object
      DashboardObject.find(params[:object_id]).destroy
    end
  end
end

app/helpers/dash_creator/application_helper.rb
module DashCreator
  module ApplicationHelper
  end
end

app/helpers/dash_creator/chart_helper.rb
module DashCreator
  module ChartHelper
    def plot_chart(id, type, plot_data, options = {})
      default_options = {
          tooltips: {
              mode: 'nearest',
              intersect: false
          },
          responsive: true
      }
      options = options.merge(default_options)
      render 'dash_creator/chart/plot_chart', {id: id, type: type, data: plot_data, options: options}
    end

    def create_update_button(id, type, text)
      button_tag text, id: "btn-#{type}-#{id}"
    end

    def update_chart_script(id, type, action_path, action_params = {})
      render 'dash_creator/chart/update_chart', {id: id, type: type, action_path: action_path, action_params: action_params}
    end

    # Data formatting (hash)
    # :labels is array of labels
    # :datasets_labels is array of datasets labels
    # :datasets is array of arrays containing the datasets data
    # for a mixed chart, :types is array of datasets types
    # :style contains chart styling
    def plot_type_1_chart(id, type, data, options = {})
      begin
        raise ArgumentError, 'datasets_key_missing' unless data.key?('datasets')
        raise ArgumentError, 'labels_key_missing' unless data.key?('labels')
        raise ArgumentError, 'types_key_missing' if (type == 'mixed' && !data.key?('types'))

        plot_data = type_1_data_to_plot(data)
      rescue Exception => e
        return render html: create_plot_error_message(id, type, e.message).to_s
      end
      plot_data_with_options = type_1_add_style(plot_data, data['style'])
      plot_data_with_options[:options] = plot_data_with_options[:options].merge(options)

      plot_chart(id, type, plot_data_with_options[:plot_data], plot_data_with_options[:options])
    end

    def type_1_data_to_plot(data)
      datasets = []
      0.upto(data['datasets'].length-1) do |i|
        set = {data: data['datasets'][i]}
        unless data['labels'][i].nil?
          set[:label] = data['datasets_labels'][i] unless data['datasets_labels'].nil?
        end
        set[:type] = data['types'][i]
        datasets.push(set)
      end

      {labels: data['labels'], datasets: datasets}
    end

    def type_1_add_style(plot_data, style_options)
      colors = style_options['colors'].nil? ? nil : set_transparency(style_options['colors'], style_options['transparencies'])

      0.upto(plot_data[:datasets].length-1) do |i|
        set = plot_data[:datasets][i]
        set[:backgroundColor] = colors[i] unless colors.nil? || colors[i].nil?
        set[:borderColor] = style_options['colors'][i] unless style_options['colors'].nil? || style_options['colors'][i].nil?
      end

      # Initialize options
      options = {}
      scales = options['scales'] = {}
      scales['xAxes'] = [{}]
      scales['yAxes'] = [{}]
      scales['xAxes'][0]['gridLines'] = {}
      scales['xAxes'][0]['ticks'] = {}
      scales['yAxes'][0]['gridLines'] = {}
      scales['yAxes'][0]['ticks'] = {}

      # Grid options
      grid_options = style_options['grid']
      scales['xAxes'][0]['gridLines']['display'] = false if grid_options['x'] == 'false'
      scales['yAxes'][0]['gridLines']['display'] = false if grid_options['y'] == 'false'

      # Y Axis options
      y_axis_options = style_options['y-axis']
      scales['yAxes'][0]['ticks']['min'] = y_axis_options['min'].to_i if y_axis_options['min'] != ''
      scales['yAxes'][0]['ticks']['max'] = y_axis_options['max'].to_i if y_axis_options['max'] != ''
      scales['yAxes'][0]['ticks']['stepSize'] = y_axis_options['step'].to_i if y_axis_options['step'] != ''

      # Stacked
      if style_options['stacked'] == 'true'
        scales['xAxes'][0]['stacked'] = true
        scales['yAxes'][0]['stacked'] = true
      end

      # Labeling step
      scales['xAxes'][0]['ticks']['callback'] = style_options['labeling-step'] if style_options['labeling-step'] != ''

      # Legend
      legend_options = style_options['legend']
      legend = options['legend'] = {}
      legend['display'] = false if legend_options['display'] == 'false'
      legend['position'] = legend_options['position']

      # Title
      options['title'] = {display: true, text: style_options['title']} if style_options['title'] != ''

      {plot_data: plot_data, options: options}
    end



    # Data formatting (hash)
    # :labels is array of labels
    # :datasets is array of arrays containing the datasets data
    # :style contains chart styling
    def plot_type_2_chart(id, type, data, options = {})
      begin
        raise ArgumentError, 'datasets_key_missing' unless data.key?('datasets')
        raise ArgumentError, 'labels_key_missing' unless data.key?('labels')

        plot_data = type_2_data_to_plot(data)
      rescue Exception => e
        return render html: create_plot_error_message(id, type, e.message).to_s
      end
      plot_data_with_options = type_2_add_style(plot_data, data['style'])
      plot_data_with_options = plot_data_with_options.merge(options)

      plot_chart(id, type, plot_data_with_options[:plot_data], plot_data_with_options[:options])
    end

    def type_2_data_to_plot(data)
      datasets = []
      0.upto(data['datasets'].length-1) do |i|
        set = {
            data: data['datasets'][i]
        }
        datasets.push(set)
      end

      {labels: data['labels'], datasets: datasets}
    end

    def type_2_add_style(plot_data, style_options)
      0.upto(plot_data[:datasets].length-1) do |i|
        set = plot_data[:datasets][i]
        set[:backgroundColor] = set_transparency(style_options['colors'], style_options['transparencies']) unless style_options['colors'].nil?
      end

      options = {}

      legend_options = style_options['legend']
      legend = options['legend'] = {}
      legend['display'] = false if legend_options['display'] == 'false'
      legend['position'] = legend_options['position']

      options['title'] = {display: true, text: style_options['title']} if style_options['title'] != ''

      {plot_data: plot_data, options: options}
    end


    # Type 1 charts & mixed bar/line
    def plot_line_chart(id, data, options = {})
      plot_type_1_chart(id, 'line', data, options)
    end

    def plot_bar_chart(id, data, options = {})
      plot_type_1_chart(id, 'bar', data, options)
    end

    def plot_mixed_chart(id, data, options = {})
      plot_type_1_chart(id, 'mixed', data, options)
    end


    # Type 2 charts
    def plot_pie_chart(id, data, options = {})
      plot_type_2_chart(id, 'pie', data, options)
    end

    def plot_doughnut_chart(id, data, options = {})
      plot_type_2_chart(id, 'doughnut', data, options)
    end

    def plot_polar_chart(id, data, options = {})
      plot_type_2_chart(id, 'polarArea', data, options)
    end

    def plot_radar_chart(id, data, options = {})
      plot_type_2_chart(id, 'radar', data, options)
    end


    # From rgb to rgba with given colors and transparencies
    def set_transparency(colors, transparencies)
      colors_with_transparency = []
      0.upto(colors.length - 1).each { |i| colors_with_transparency.push('rgba' + colors[i][3..-2] + ', ' + (1-(transparencies[i].to_f/100)).to_s + ')') }
      colors_with_transparency
    end

    # Returns plot failing error message
    def create_plot_error_message(id, type, error_key)
      str = error_key + " for chart-#{type}-#{id}"
      str
    end


    # Data processing for charts
    # Handle differently regarding x_data type
    def chart_processing(data)
      ActiveRecord::Base.connection.execute("SET temp_buffers = '4GB';")
      case data['x_data']['type']
        when 'datetime'
          hash = date_chart_processing(data)

        when 'numeric'
          hash = numeric_chart_processing(data)

        when 'boolean'
          hash = boolean_chart_processing(data)

        when 'text'
          hash = text_chart_processing(data)

        when 'has'
          hash = has_model_chart_processing(data)

        when 'ref'
          hash = ref_model_chart_processing(data)

        else
          hash = {}
      end
      ActiveRecord::Base.connection.execute("SET temp_buffers = '8MB';")
      hash = hash.merge({
                            datasets_labels: data['datasets_labels'],
                            types: data['types']
                        })
      hash
    end

    def get_start_and_end_dates(date_info)
      date_range_type = date_info['date_range_type']

      case date_range_type
        when 'Today'
          start_date = DateTime.now.beginning_of_day
          end_date = DateTime.now.beginning_of_day + 1.days

        when 'Yesterday'
          start_date = DateTime.now.beginning_of_day - 1.days
          end_date = DateTime.now.beginning_of_day

        when 'Last 7 Days'
          start_date = DateTime.now.beginning_of_day - 6.days
          end_date = DateTime.now.beginning_of_day + 1.days

        when 'This Week'
          start_date = DateTime.now.beginning_of_week
          end_date = DateTime.now.beginning_of_week + 7.days

        when 'Last Week'
          start_date = DateTime.now.beginning_of_week - 7.days
          end_date = DateTime.now.beginning_of_week

        when 'Last 30 Days'
          start_date = DateTime.now.beginning_of_day - 29.days
          end_date = DateTime.now.beginning_of_day + 1.days

        when 'This Month'
          start_date = DateTime.now.beginning_of_month
          end_date = DateTime.now.beginning_of_month + 30.days

        when 'Last Month'
          start_date = DateTime.now.beginning_of_month - 30.days
          end_date = DateTime.now.beginning_of_month

        when 'Last 365 Days'
          start_date = DateTime.now.beginning_of_day - 364.days
          end_date = DateTime.now.beginning_of_day + 1.days

        when 'This Year'
          start_date = DateTime.now.beginning_of_year
          end_date = DateTime.now.beginning_of_year + 365.days

        when 'Last Year'
          start_date = DateTime.now.beginning_of_year - 365.days

app/helpers/dash_creator/dashboard_helper.rb
module DashCreator
  module DashboardHelper
  end
end

app/helpers/dash_creator/dashboard_object_helper.rb
module DashCreator
  module DashboardObjectHelper
  end
end

app/helpers/dash_creator/user_helper.rb
module DashCreator
  module UserHelper
  end
end

app/views/dash_creator/chart/_chart_creator.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        Super Amazing Chart Creator
      </div>
      <div class="card-block" id="chart-creator" style="margin:20px 50px;">

      </div>
      <div class="card-footer">
        <button type="submit" class="pull-left btn btn-success" id="chart-submit-btn">Draw Chart</button>
        <a href="#" data-toggle="modal" data-target="#delete_charts_modal" class="pull-right btn btn-sm btn-danger" id="chart-unsave-btn"><%=t :delete_charts%></a>
        <a href="#" data-toggle="modal" data-target="#edit_chart_modal" class="pull-right btn btn-sm btn-primary" id="chart-edit-btn"><%=t :modify_chart%></a>
        <a href="#" data-toggle="modal" data-target="#save_chart_modal" class="pull-right btn btn-sm btn-success"><%=t :save_new_chart%></a>
        <%= select_tag 'chart-select', options_for_select([]), prompt: 'Choose a chart', id: '', class: 'form-control pull-right', style: 'width: 20%; margin-right: 10%;' %>
      </div>
    </div>
    <!--/.card-->
  </div>
</div>

<script>
    var charts = <%= raw @charts %>;

    // TODO: JSON handling ??
    // TODO: for date charts, always calculate day values and then gather ? so that changing day/week/month display doesn't need a reload
    // TODO: if only bar/line change don't refresh
    // TODO: Stats creator: take a filter, simply return the count of objects
    // TODO: minicolors issue ?? Too much JS to handle for the browser when many color fields in chart creator

    // Style presets
    var minicolors_swatches = [
        'rgb(255, 99, 132)',
        'rgb(54, 162, 235)',
        'rgb(255, 206, 86)',
        'rgb(75, 192, 192)',
        'rgb(153, 102, 255)',
        'rgb(255, 159, 64)',
        'rgb(216, 247, 147)',
        'rgb(52, 85, 17)',
        'rgb(220, 255, 253)',
        'rgb(1, 17, 10)',
        'rgb(219, 153, 90)',
        'rgb(153, 134, 80)'
    ];
    var minicolors_options = {theme: 'bootstrap', format: 'rgb', swatches: minicolors_swatches};

    $('#chart-creator').chartCreator({
        models_data: <%= raw @models_data.to_json %>,
        attributes_aliases: <%= raw DashCreator.attributes_aliases.to_json %>,
        displayed_model_names: <%= raw DashCreator.displayed_model_names.to_json %>,
        displayed_attribute_names: <%= raw DashCreator.displayed_attribute_names.to_json %>,
        filter_creator: $('#filter-creator'),
        minicolors_options: minicolors_options
    });
    var chart_creator = $('#chart-creator').data('chartCreator');


    // --------------- Send chart data to controller ---------------
    chart_creator.labelOptionsContainer.on('click', '#pluck-labels-btn', labelsFromPluck);
    function labelsFromPluck() {
        var limit = chart_creator.labelOptionsContainer.find('[name="pluck-num"]').val();

        var x = chart_creator.xContainer.find('[name="x-axis"]').val().split('-');
        var model, attribute;
        if (x[1] === 'has' || x[1] === 'ref') {
            model = x[0].classify();
            attribute = chart_creator.labelOptionsContainer.find('[name="x-sub"]').val().split('-')[0];
        }
        else {
            model = chart_creator.yContainer.find('[name="y-axis"]:first').val();
            attribute = x[0];
        }

        var params = {
            model: model,
            attribute: attribute,
            limit: limit
        };

        $.post('<%= pluck_labels_path %>', params, function(data) {
            var labels = data['labels'];

            chart_creator.labelOptionsContainer.find('[name="labels-num"]').val(labels.length).change();
            chart_creator.labelOptionsContainer.find('.limit-label').each(function() {
                $(this).val(labels.shift());
            });
        });
    }


    // --------------- Send chart data to controller ---------------
    // Send data for controller chart actions
    function sendChartDataCreate(chart_data) {
        $.post("<%= create_chart_path %>", chart_data);
    }

    function sendChartDataSave(chart_data) {
        $.post("<%= save_chart_path %>", chart_data, function(data) {
            var chart_id = data['chart_id'], chart_name = chart_data['chart_name'];
            charts.push([chart_name, chart_id]);

            var dashboard_creator_objects_data = $('#dashboard-creator').data('dashboardCreator').objects_data;
            dashboard_creator_objects_data['chart']['objects'].push({id: chart_id, name: chart_name});
        });
    }

    function sendChartDataEdit(chart_data) {
        $.post("<%= edit_chart_path %>", chart_data);
    }

    // Handle submit
    $('#chart-submit-btn').click(function() {
        var chart_data = chart_creator.getChartData();
        chart_data['refresh'] = false;
        sendChartDataCreate(chart_data);
    });


    // --------------- Save, unsave, show saved charts ---------------
    var chart_id = '';

    // Save a chart config
    $(document).on('click', '#save-chart-btn', function() {
        var chart_data = chart_creator.getChartData();

        // Get the chart name
        chart_data['chart_name'] = $('.modal#save_chart_modal').find('[name="chart-name"]').val();

        // Post data with chart-save request
        sendChartDataSave(chart_data);
    });

    // Prepare modal display for edit
    $('#chart-edit-btn').click(function() {
        var confirm_edit_chart_btn = $('#confirm-edit-chart-btn');

        var h3_div = $('.modal#edit_chart_modal .modal-body #edit-message');
        h3_div.empty();
        confirm_edit_chart_btn.prop('disabled', false);

        var h3_div_text;
        if (chart_id !== '') {
            h3_div_text = 'Are you sure you want to edit chart ';
            for (var i = 0; i < charts.length; i++) {
                var chart_name = charts[i][0], id = charts[i][1];
                if (chart_id === id) {
                    h3_div_text += chart_name;
                    break;
                }
            }
            h3_div_text += ' ?'
        }
        else {
            h3_div_text = 'No chart to edit.';
            confirm_edit_chart_btn.prop('disabled', true);
        }
        h3_div.text(h3_div_text);
    });

    // Prepare and send new chart data on chart edit confirm
    $(document).on('click', '#confirm-edit-chart-btn', function() {
        var chart_data = chart_creator.getChartData();
        chart_data['chart_id'] = chart_id;

        sendChartDataEdit(chart_data);
    });

    // Prepare list of charts for delete charts modal
    $('#chart-unsave-btn').click(function() {
        var checkbox_list = $('#charts-checkbox-list');
        // First empty the checkbox list
        checkbox_list.children().remove();

        // Append charts list to div in modal
        var checkbox_string_start = '<div class="col-sm-12"><div class="form-group">'
            + '<input type="checkbox" class="form-control" name="chart" value="';
        for (var i = 0; i < charts.length; i++) {
            var chart_name = charts[i][0], id = charts[i][1];
            var chart_string = checkbox_string_start + id + '"><label>' + chart_name + '</label><br>';
            $(chart_string).appendTo(checkbox_list);
        }
        $('</div></div>').appendTo(checkbox_list);
    });

    // Delete charts
    $(document).on('click', '#delete-charts-btn', function() {
        // Get the charts ids
        var charts_ids = [];
        $(this).closest('.modal').find('[type="checkbox"]:checked').each(function() {
            charts_ids.push($(this).attr("value"));
        });

        var params = {charts_ids: charts_ids};

        $.post("<%= delete_charts_path %>", params, function() {
            // Remove from charts list
            for (var i = 0; i < charts.length; i++) {
                var id = charts[i][1];
                if ($.inArray(id, charts_ids) !== -1) {
                    charts.splice(i, 1);
                    i--;
                }
            }
        });
    });

    $('[name="chart-select"]')
        .focusin(displayChartList)
        .change(displayChart);

    // Display chart select list
    function displayChartList() {
        $(this).children().not('[value=""]').remove();
        for (var i = 0; i < charts.length; i++) {
            var chart_name = charts[i][0], id = charts[i][1];
            $('<option value="' + id + '">' + chart_name + '</option>').appendTo($('[name="chart-select"]'));
        }
    }

    // Display chosen chart
    function displayChart() {
        if ($(this).val() === '') { return false; }

        chart_id = $(this).val();
        var params = {chart_id: chart_id};

        $.post("<%= get_chart_path %>", params);
    }
</script>

app/views/dash_creator/chart/create_chart.js.erb
var in_creator = $('#chart-creator').length !== 0;

// Rebuild all chart creator fields if in creator
if (in_creator) {
    var chart_creator = $('#chart-creator').data('chartCreator');
    <% unless filters_data.nil? %>
    chart_creator.filter_creator.data('filterCreator').buildFilters(<%= raw filters_data.to_json %>);
    <% end %>
    chart_creator.buildChartFields(<%= raw chart_data.to_json %>);
}

<% # Get main chart type %>
<% main_type = chart_data['types'][0] %>
<% main_type = 'mixed' if main_type == 'bar' || main_type == 'line' %>

<% options = chart_data['options'] == '' ? {} : chart_data['options'] %>

<% # Get data from redis if exists or query it %>
<% processed_data = chart_processed_data_from_redis(chart_data) %>

// Build chart script & append it to chart wrapper div
<% function_name = "plot_#{main_type}_chart" %>
var chart_script_string = '<%= raw public_send(function_name, id, processed_data, options).gsub("\n", '') %>';

var chart_wrapper_div = in_creator ? $('.chart-wrapper') : $('.chart-wrapper[data-id="<%= id %>"]');

chart_wrapper_div.children().remove();
$(chart_script_string).appendTo(chart_wrapper_div);

// Refresh option
chart_wrapper_div
    .off('click')                                           // Remove previous bound refresh event
    .on('click', '#chart-refresh-btn', refreshChart);       // Bind refresh event

function refreshChart() {
    if (in_creator) {
        var chart_data = chart_creator.getChartData();
        chart_data['refresh'] = true;
        sendChartDataCreate(chart_data);
    }
    else {
        var params = {
            chart_id: '<%= id %>',
            refresh: 'true'
        };
        $.post("<%= get_chart_path %>", params);
    }
}

chart_wrapper_div.find('span#last-updated').text('Last updated: ' + "<%= processed_data['last_updated'] %>");


<% # DashCreator.redis_store_variable.keys.each {|k| $redis.del(k)}   # To delete what is stored in redis %>