config/routes.rb
DashCreator::Engine.routes.draw do
  root to: 'user#creator'

  get '/creator', to: 'user#creator', as: :creator
  get '/dashboard/:dashboard_id', to: 'user#dashboard', as: :dashboard

  post '/get_filter', to: 'filter#get_filter', as: :get_filter
  post '/save_filter', to: 'filter#save_filter', as: :save_filter
  post '/delete_filters', to: 'filter#delete_filters', as: :delete_filters

  post '/filtering_result', to: 'filter#filtering_result', as: :filtering_result
  get '/download_csv', to: 'filter#download_csv', as: :download_csv

  post '/create_stat', to: 'filter#create_stat', as: :create_stat

  post '/create_chart', to: 'chart#create_chart', as: :create_chart
  post '/save_chart', to: 'chart#save_chart', as: :save_chart
  post '/edit_chart', to: 'chart#edit_chart', as: :edit_chart
  post '/get_chart', to: 'chart#get_chart', as: :get_chart
  post '/delete_charts', to: 'chart#delete_charts', as: :delete_charts

  post '/pluck_labels', to: 'chart#pluck_labels', as: :pluck_labels

  post '/save_dashboard', to: 'dashboard#save_dashboard', as: :save_dashboard
  post '/edit_dashboard', to: 'dashboard#edit_dashboard', as: :edit_dashboard
  post '/get_dashboard', to: 'dashboard#get_dashboard', as: :get_dashboard
  post '/delete_dashboards', to: 'dashboard#delete_dashboards', as: :delete_dashboards

  post '/get_model_objects', to: 'dashboard_object#get_model_objects', as: :get_model_objects
end

app/models/dash_creator/application_record.rb
module DashCreator
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/dash_creator/dashboard_object.rb
module DashCreator
  class DashboardObject < ApplicationRecord
    validates_presence_of :code, unique: true

    # Acts as dashboard object for objects you want to display in your dashboard
  end
end

app/controllers/dash_creator/application_controller.rb
class DashCreator::ApplicationController < ::ApplicationController
  protect_from_forgery with: :exception
end

app/controllers/dash_creator/chart_controller.rb
require_dependency "dash_creator/application_controller"

module DashCreator
  class ChartController < ApplicationController
    skip_before_action :verify_authenticity_token
    
    def create_chart
      return render json: {models: nil} if params[:filters].nil?

      # Remove useless filters from data
      chart_data = params
      chart_data[:filters] = chart_data[:filters]
                                 .to_unsafe_h
                                 .select { |key, value| chart_data[:y_data].include?(key.to_s) || (key.to_s == chart_data[:x_data][:attribute].classify && chart_data[:x_data][:from_filter] == 'true' ) }

      render 'dash_creator/chart/create_chart', locals: {chart_data: chart_data, filters_data: nil, id: 0}
    end

    def save_chart
      return render json: {models: nil} if params[:filters].nil?

      # Remove useless filters from data
      chart_data = params
      chart_data[:filters] = chart_data[:filters]
                                 .to_unsafe_h
                                 .select { |key, value| chart_data[:y_data].include?(key.to_s) || (key.to_s == chart_data[:x_data][:attribute].classify && chart_data[:x_data][:from_filter] == 'true' ) }

      # Create chart from data
      user = user_for_dash_creator
      chart = DashCreator::Chart.all.where(user_id: user.id).create(name: params[:chart_name], data: chart_data)

      render json: {chart_id: chart.id}
    end

    def edit_chart
      return render json: {models: nil} if params[:filters].nil?

      # Remove useless filters from data
      chart_data = params
      chart_data[:filters] = chart_data[:filters]
                                 .to_unsafe_h
                                 .select { |key, value| chart_data[:y_data].include?(key.to_s) || (key.to_s == chart_data[:x_data][:attribute].classify && chart_data[:x_data][:from_filter] == 'true' ) }

      # Edit chart from data
      user = user_for_dash_creator
      chart = DashCreator::Chart.all.where(user_id: user.id).find(params[:chart_id])
      chart.update_attribute(:data, chart_data)

      render json: {chart_id: chart.id}
    end

    def get_chart
      user = user_for_dash_creator
      id = params[:chart_id]
      chart = DashCreator::Chart.all.where(user_id: user.id).find(id)
      refresh = params.key?('refresh') ? params['refresh'] : 'false'

      filters_data = chart.data['filters']

      chart_data = chart.data
      chart_data['refresh'] = refresh
      chart_data.delete('chart_id')
      chart_data.delete('chart_name')

      render 'dash_creator/chart/create_chart', locals: {chart_data: chart.data, filters_data: filters_data, id: id}
    end

    def delete_charts
      user = user_for_dash_creator
      DashCreator::Chart.all.where(user_id: user.id, id: params[:charts_ids]).destroy_all
    end

    def pluck_labels
      model = params[:model].safe_constantize
      attribute = params[:attribute]
      limit = params[:limit].empty? ? 30 : params[:limit].to_i

      render json: {labels: model.pluck(:"#{attribute}").uniq.take(limit)}
    end
  end
end

app/controllers/dash_creator/dashboard_controller.rb
require_dependency "dash_creator/application_controller"

module DashCreator
  class DashboardController < ApplicationController
    skip_before_action :verify_authenticity_token

    def get_dashboard
      # user = user_for_dash_creator
      # dashboard = DashCreator::Dashboard.all.where(user_id: user.id).find(params[:dashboard_id])
      dashboard = DashCreator::Dashboard.all.find(params[:dashboard_id])

      render json: dashboard.options
    end

    def save_dashboard
      user = user_for_dash_creator
      dashboard = DashCreator::Dashboard.all.where(user_id: user.id).create(name: params[:dashboard_name], options: params[:options])

      render json: {dashboard_id: dashboard.id}
    end

    def edit_dashboard
      # user = user_for_dash_creator
      # dashboard = DashCreator::Dashboard.all.where(user_id: user.id).find(params[:dashboard_id])
      dashboard = DashCreator::Dashboard.all.find(params[:dashboard_id])
      dashboard.update_attribute(:options, params[:options])

      render json: {dashboard_id: dashboard.id}
    end

    def delete_dashboards
      # user = user_for_dash_creator
      # DashCreator::Dashboard.all.where(user_id: user.id, id: params[:dashboards_ids]).destroy_all
      DashCreator::Dashboard.all.where(id: params[:dashboards_ids]).destroy_all
    end
  end
end

app/controllers/dash_creator/dashboard_object_controller.rb
require_dependency "dash_creator/application_controller"

module DashCreator
  class DashboardObjectController < ApplicationController
    skip_before_action :verify_authenticity_token

    def get_model_objects
      object = DashboardObject.find_by_code(params['object_code'])

      model_objects = object.related_model.classify.safe_constantize.all

      model_objects_json = model_objects.map{ |o| {id: o.id, name: o.name} }

      render json: {model_objects: model_objects_json}
    end

    def save_object
      object = DashboardObject.create(name: params[:name], options: params[:options])

      render json: {object_id: object.id}
    end

    def edit_object
      object = DashboardObject.find_by_code(params['object_code'])
      object.update_attribute(:options, params[:options])

      render json: {object_id: object.id}
    end

    def delete_object
      DashboardObject.find(params[:object_id]).destroy
    end
  end
end

app/helpers/dash_creator/application_helper.rb
module DashCreator
  module ApplicationHelper
  end
end

app/helpers/dash_creator/chart_helper.rb
module DashCreator
  module ChartHelper
    def plot_chart(id, type, plot_data, options = {})
      default_options = {
          tooltips: {
              mode: 'nearest',
              intersect: false
          },
          responsive: true
      }
      options = options.merge(default_options)
      render 'dash_creator/chart/plot_chart', {id: id, type: type, data: plot_data, options: options}
    end

    def create_update_button(id, type, text)
      button_tag text, id: "btn-#{type}-#{id}"
    end

    def update_chart_script(id, type, action_path, action_params = {})
      render 'dash_creator/chart/update_chart', {id: id, type: type, action_path: action_path, action_params: action_params}
    end

    # Data formatting (hash)
    # :labels is array of labels
    # :datasets_labels is array of datasets labels
    # :datasets is array of arrays containing the datasets data
    # for a mixed chart, :types is array of datasets types
    # :style contains chart styling
    def plot_type_1_chart(id, type, data, options = {})
      begin
        raise ArgumentError, 'datasets_key_missing' unless data.key?('datasets')
        raise ArgumentError, 'labels_key_missing' unless data.key?('labels')
        raise ArgumentError, 'types_key_missing' if (type == 'mixed' && !data.key?('types'))

        plot_data = type_1_data_to_plot(data)
      rescue Exception => e
        return render html: create_plot_error_message(id, type, e.message).to_s
      end
      plot_data_with_options = type_1_add_style(plot_data, data['style'])
      plot_data_with_options[:options] = plot_data_with_options[:options].merge(options)

      plot_chart(id, type, plot_data_with_options[:plot_data], plot_data_with_options[:options])
    end

    def type_1_data_to_plot(data)
      datasets = []
      0.upto(data['datasets'].length-1) do |i|
        set = {data: data['datasets'][i]}
        unless data['labels'][i].nil?
          set[:label] = data['datasets_labels'][i] unless data['datasets_labels'].nil?
        end
        set[:type] = data['types'][i]
        datasets.push(set)
      end

      {labels: data['labels'], datasets: datasets}
    end

    def type_1_add_style(plot_data, style_options)
      colors = style_options['colors'].nil? ? nil : set_transparency(style_options['colors'], style_options['transparencies'])

      0.upto(plot_data[:datasets].length-1) do |i|
        set = plot_data[:datasets][i]
        set[:backgroundColor] = colors[i] unless colors.nil? || colors[i].nil?
        set[:borderColor] = style_options['colors'][i] unless style_options['colors'].nil? || style_options['colors'][i].nil?
      end

      # Initialize options
      options = {}
      scales = options['scales'] = {}
      scales['xAxes'] = [{}]
      scales['yAxes'] = [{}]
      scales['xAxes'][0]['gridLines'] = {}
      scales['xAxes'][0]['ticks'] = {}
      scales['yAxes'][0]['gridLines'] = {}
      scales['yAxes'][0]['ticks'] = {}

      # Grid options
      grid_options = style_options['grid']
      scales['xAxes'][0]['gridLines']['display'] = false if grid_options['x'] == 'false'
      scales['yAxes'][0]['gridLines']['display'] = false if grid_options['y'] == 'false'

      # Y Axis options
      y_axis_options = style_options['y-axis']
      scales['yAxes'][0]['ticks']['min'] = y_axis_options['min'].to_i if y_axis_options['min'] != ''
      scales['yAxes'][0]['ticks']['max'] = y_axis_options['max'].to_i if y_axis_options['max'] != ''
      scales['yAxes'][0]['ticks']['stepSize'] = y_axis_options['step'].to_i if y_axis_options['step'] != ''

      # Stacked
      if style_options['stacked'] == 'true'
        scales['xAxes'][0]['stacked'] = true
        scales['yAxes'][0]['stacked'] = true
      end

      # Labeling step
      scales['xAxes'][0]['ticks']['callback'] = style_options['labeling-step'] if style_options['labeling-step'] != ''

      # Legend
      legend_options = style_options['legend']
      legend = options['legend'] = {}
      legend['display'] = false if legend_options['display'] == 'false'
      legend['position'] = legend_options['position']

      # Title
      options['title'] = {display: true, text: style_options['title']} if style_options['title'] != ''

      {plot_data: plot_data, options: options}
    end



    # Data formatting (hash)
    # :labels is array of labels
    # :datasets is array of arrays containing the datasets data
    # :style contains chart styling
    def plot_type_2_chart(id, type, data, options = {})
      begin
        raise ArgumentError, 'datasets_key_missing' unless data.key?('datasets')
        raise ArgumentError, 'labels_key_missing' unless data.key?('labels')

        plot_data = type_2_data_to_plot(data)
      rescue Exception => e
        return render html: create_plot_error_message(id, type, e.message).to_s
      end
      plot_data_with_options = type_2_add_style(plot_data, data['style'])
      plot_data_with_options = plot_data_with_options.merge(options)

      plot_chart(id, type, plot_data_with_options[:plot_data], plot_data_with_options[:options])
    end

    def type_2_data_to_plot(data)
      datasets = []
      0.upto(data['datasets'].length-1) do |i|
        set = {
            data: data['datasets'][i]
        }
        datasets.push(set)
      end

      {labels: data['labels'], datasets: datasets}
    end

    def type_2_add_style(plot_data, style_options)
      0.upto(plot_data[:datasets].length-1) do |i|
        set = plot_data[:datasets][i]
        set[:backgroundColor] = set_transparency(style_options['colors'], style_options['transparencies']) unless style_options['colors'].nil?
      end

      options = {}

      legend_options = style_options['legend']
      legend = options['legend'] = {}
      legend['display'] = false if legend_options['display'] == 'false'
      legend['position'] = legend_options['position']

      options['title'] = {display: true, text: style_options['title']} if style_options['title'] != ''

      {plot_data: plot_data, options: options}
    end


    # Type 1 charts & mixed bar/line
    def plot_line_chart(id, data, options = {})
      plot_type_1_chart(id, 'line', data, options)
    end

    def plot_bar_chart(id, data, options = {})
      plot_type_1_chart(id, 'bar', data, options)
    end

    def plot_mixed_chart(id, data, options = {})
      plot_type_1_chart(id, 'mixed', data, options)
    end


    # Type 2 charts
    def plot_pie_chart(id, data, options = {})
      plot_type_2_chart(id, 'pie', data, options)
    end

    def plot_doughnut_chart(id, data, options = {})
      plot_type_2_chart(id, 'doughnut', data, options)
    end

    def plot_polar_chart(id, data, options = {})
      plot_type_2_chart(id, 'polarArea', data, options)
    end

    def plot_radar_chart(id, data, options = {})
      plot_type_2_chart(id, 'radar', data, options)
    end


    # From rgb to rgba with given colors and transparencies
    def set_transparency(colors, transparencies)
      colors_with_transparency = []
      0.upto(colors.length - 1).each { |i| colors_with_transparency.push('rgba' + colors[i][3..-2] + ', ' + (1-(transparencies[i].to_f/100)).to_s + ')') }
      colors_with_transparency
    end

    # Returns plot failing error message
    def create_plot_error_message(id, type, error_key)
      str = error_key + " for chart-#{type}-#{id}"
      str
    end


    # Data processing for charts
    # Handle differently regarding x_data type
    def chart_processing(data)
      ActiveRecord::Base.connection.execute("SET temp_buffers = '4GB';")
      case data['x_data']['type']
        when 'datetime'
          hash = date_chart_processing(data)

        when 'numeric'
          hash = numeric_chart_processing(data)

        when 'boolean'
          hash = boolean_chart_processing(data)

        when 'text'
          hash = text_chart_processing(data)

        when 'has'
          hash = has_model_chart_processing(data)

        when 'ref'
          hash = ref_model_chart_processing(data)

        else
          hash = {}
      end
      ActiveRecord::Base.connection.execute("SET temp_buffers = '8MB';")
      hash = hash.merge({
                            datasets_labels: data['datasets_labels'],
                            types: data['types']
                        })
      hash
    end

    def get_start_and_end_dates(date_info)
      date_range_type = date_info['date_range_type']

      case date_range_type
        when 'Today'
          start_date = DateTime.now.beginning_of_day
          end_date = DateTime.now.beginning_of_day + 1.days

        when 'Yesterday'
          start_date = DateTime.now.beginning_of_day - 1.days
          end_date = DateTime.now.beginning_of_day

        when 'Last 7 Days'
          start_date = DateTime.now.beginning_of_day - 6.days
          end_date = DateTime.now.beginning_of_day + 1.days

        when 'This Week'
          start_date = DateTime.now.beginning_of_week
          end_date = DateTime.now.beginning_of_week + 7.days

        when 'Last Week'
          start_date = DateTime.now.beginning_of_week - 7.days
          end_date = DateTime.now.beginning_of_week

        when 'Last 30 Days'
          start_date = DateTime.now.beginning_of_day - 29.days
          end_date = DateTime.now.beginning_of_day + 1.days

        when 'This Month'
          start_date = DateTime.now.beginning_of_month
          end_date = DateTime.now.beginning_of_month + 30.days

        when 'Last Month'
          start_date = DateTime.now.beginning_of_month - 30.days
          end_date = DateTime.now.beginning_of_month

        when 'Last 365 Days'
          start_date = DateTime.now.beginning_of_day - 364.days
          end_date = DateTime.now.beginning_of_day + 1.days

        when 'This Year'
          start_date = DateTime.now.beginning_of_year
          end_date = DateTime.now.beginning_of_year + 365.days

        when 'Last Year'
          start_date = DateTime.now.beginning_of_year - 365.days

app/helpers/dash_creator/dashboard_helper.rb
module DashCreator
  module DashboardHelper
  end
end

app/helpers/dash_creator/dashboard_object_helper.rb
module DashCreator
  module DashboardObjectHelper
  end
end

app/helpers/dash_creator/user_helper.rb
module DashCreator
  module UserHelper
  end
end

app/views/dash_creator/dashboard/_dashboard_creator.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        Crazy Dashboard Creator
      </div>
      <div class="card-block" id="dashboard-creator" style="margin:20px 50px;">

      </div>
      <div class="card-footer">
        <a href="#" data-toggle="modal" data-target="#delete_dashboards_modal" class="pull-right btn btn-sm btn-danger" id="dashboard-unsave-btn"><%=t :delete_dashboards%></a>
        <a href="#" data-toggle="modal" data-target="#edit_dashboard_modal" class="pull-right btn btn-sm btn-primary" id="dashboard-edit-btn"><%=t :modify_dashboard%></a>
        <a href="#" data-toggle="modal" data-target="#save_dashboard_modal" class="pull-right btn btn-sm btn-success"><%=t :save_new_dashboard%></a>
        <%= select_tag 'dashboard-select', options_for_select([]), prompt: 'Choose a dashboard', id: '', class: 'form-control pull-right', style: 'width: 20%; margin-right: 10%;' %>
      </div>
    </div>
    <!--/.card-->
  </div>

  <!--<div class="col-md-12">-->
    <!--<div class="card" id="crazy-dashboard-creator-objects">-->
      <!--<div class="card-header">-->
        <!--Dashboard Objects-->
      <!--</div>-->
      <!--<div class="card-block" style="margin:20px 50px;">-->
        <!--<div class="row">-->
          <!--<div class="col-md-12 px-2">-->
            <!--<table>-->
              <!--<thead>-->
              <!--<tr>-->
                <!--<th><%=t :name%></th>-->
                <!--<th><%=t :code%></th>-->
                <!--<th><%=t :information%></th>-->
                <!--<th><%=t :options%></th>-->
                <!--<th><%=t :edit%></th>-->
                <!--<th><%=t :delete%></th>-->
              <!--</thead>-->
              <!--<tbody>-->
              <!---->
              <!--</tbody>-->
            <!--</table>-->
          <!--</div>-->
        <!--</div>-->
      <!--</div>-->
    <!--</div>-->
    <!--</div>-->
    <!--&lt;!&ndash;/.card&ndash;&gt;-->
  <!--</div>-->
</div>

<script>
    var dashboards = <%= raw @dashboards %>;

    <% objects_data = {} %>
    <% @dashboard_objects.each do |o| %>
        <% objects_data[o.code] = {name: o.name, related_model: o.related_model, objects: @model_objects[o.code] } %>
    <% end %>

    $('#dashboard-creator').dashboardCreator({
        objects_data: <%= raw objects_data.to_json %>
    });
    var dashboard_creator = $('#dashboard-creator').data('dashboardCreator');


    // --------------- Dashboard model handling ---------------

    var dashboard_id = '';

    // Save dashboard
    $(document).on('click', '#save-dashboard-btn', function() {
        var params = {options: dashboard_creator.getDashboardData()};

        // Get the dashboard name
        params['dashboard_name'] = $('.modal#save_dashboard_modal').find('[name="dashboard-name"]').val();

        $.post("<%= save_dashboard_path %>", params, function(data) {
            // Add to dashboards list
            dashboard_id = data['dashboard_id'];
            dashboards.push([params['dashboard_name'], dashboard_id]);
        });
    });

    // Prepare modal display for edit
    $('#dashboard-edit-btn').click(function() {
        var confirm_edit_dashboard_btn = $('#confirm-edit-dashboard-btn');

        var message_div = $('.modal#edit_dashboard_modal .modal-body #edit-message');
        message_div.empty();
        confirm_edit_dashboard_btn.prop('disabled', false);

        var message;
        if (dashboard_id !== '') {
            message = 'Are you sure you want to edit dashboard ';
            for (var i = 0; i < dashboards.length; i++) {
                var dashboard_name = dashboards[i][0], id = dashboards[i][1];
                if (dashboard_id === id) {
                    message += dashboard_name;
                    break;
                }
            }
            message += ' ?'
        }
        else {
            message = 'No dashboard to edit.';
            confirm_edit_dashboard_btn.prop('disabled', true);
        }
        message_div.text(message);
    });

    // Prepare and send new dashboard data on dashboard edit confirm
    $(document).on('click', '#confirm-edit-dashboard-btn', function() {
        var params = {options: dashboard_creator.getDashboardData()};
        params['dashboard_id'] = dashboard_id;

        $.post("<%= edit_dashboard_path %>", params);
    });

    // Prepare list of dashboards for delete dashboards modal
    $('#dashboard-unsave-btn').click(function() {
        var dashboards_checkbox_list = $('#dashboards-checkbox-list');
        // First empty the checkbox list
        dashboards_checkbox_list.children().remove();

        // Append dashboards list to div in modal
        var checkbox_string_start = '<div class="col-sm-12"><div class="form-group">'
            + '<input type="checkbox" class="form-control" name="dashboard" value="';
        for (var i = 0; i < dashboards.length; i++) {
            var dashboard_name = dashboards[i][0], id = dashboards[i][1];
            var dashboard_string = checkbox_string_start + id + '"><label>' + dashboard_name + '</label><br>';
            $(dashboard_string).appendTo(dashboards_checkbox_list);
        }
        $('</div></div>').appendTo(dashboards_checkbox_list);
    });

    // Delete dashboards configs
    $(document).on('click', '#delete-dashboards-btn', function() {
        // Get the dashboards ids
        var dashboards_ids = [];
        $(this).closest('.modal').find('[name="dashboard"]:checked').each(function() {
            dashboards_ids.push($(this).attr("value"));
        });

        var params = {dashboards_ids: dashboards_ids};

        $.post("<%= delete_dashboards_path %>", params, function() {
            // Remove from dashboards list
            for (var i = 0; i < dashboards.length; i++) {
                var id = dashboards[i][1];
                if ($.inArray(id, dashboards_ids) !== -1) {
                    dashboards.splice(i, 1);
                    i--;
                }
            }
        });
    });


    $('[name="dashboard-select"]')
        .focusin(displaySavedDashboards)
        .change(displayDashboard);

    // Display saved configs
    function displaySavedDashboards() {
        $(this).children('option').not('[value=""]').remove();
        for (var i = 0; i < dashboards.length; i++) {
            var dashboard_name = dashboards[i][0], id = dashboards[i][1];
            $('<option value="' + id + '">' + dashboard_name + '</option>').appendTo($('[name="dashboard-select"]'));
        }
    }

    // Display chosen config (rebuild)
    function displayDashboard() {
        if ($(this).val() === '') { return false; }

        dashboard_id = $(this).val();
        var params = {dashboard_id: dashboard_id};

        $.post("<%= get_dashboard_path %>", params, function(data) {
            dashboard_creator.buildDashboard(data);
        });
    }
</script>

app/views/dash_creator/dashboard/_modals.html.erb
<div class="modal fade" id="save_dashboard_modal" tabindex="-1" role="dialog" aria-labelledby="Save Dashboard Modal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><%=t :save_dashboard%></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <label><%=t :name%></label>
              <input type="text" name="dashboard-name" class="form-control">
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="pull-right btn btn-success" id="save-dashboard-btn" data-dismiss="modal">Submit</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="modal fade" id="delete_dashboards_modal" tabindex="-1" role="dialog" aria-labelledby="Delete Dashboards Modal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><%=t :delete_dashboards%></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row" id="dashboards-checkbox-list">
        </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="pull-right btn btn-success" id="delete-dashboards-btn" data-dismiss="modal">Submit</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="modal fade" id="edit_dashboard_modal" tabindex="-1" role="dialog" aria-labelledby="Edit Dashboard Modal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><%=t :edit_dashboard%></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <h3 id="edit-message"></h3>
      </div>
      <div class="modal-footer">
        <button type="submit" class="pull-left btn btn-success" id="confirm-edit-dashboard-btn" data-dismiss="modal">Confirm</button>
        <button type="submit" class="pull-right btn btn-danger" id="cancel-edit-dashboard-btn" data-dismiss="modal">Cancel</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->